-- =============================================================================
-- VISTAS SQL — RETIRADAS (docs/V1-REMOVAL-PLAN.md, Fase 2, jul 2026)
-- =============================================================================
--
-- Este archivo definía 4 vistas 100% V1 (players / player_registrations /
-- player_season_stats / match_events), creadas a mano en Supabase (no vía
-- migraciones Drizzle): player_league_stats, player_global_stats,
-- league_standings, league_top_scorers.
--
-- Ninguna tiene lector en `src/` (confirmado por grep exhaustivo antes de
-- este cambio) — la única que sí estaba modelada en Drizzle (`playerGlobalStats`,
-- pgView en schema.ts) se retiró en el mismo paso.
--
-- Como se crearon a mano, dropearlas también es manual. Correr esto UNA VEZ
-- en Supabase (orden por dependencia: las que dependen de player_league_stats
-- primero):
--
--   DROP VIEW IF EXISTS league_top_scorers;
--   DROP VIEW IF EXISTS player_global_stats;
--   DROP VIEW IF EXISTS player_league_stats;
--   DROP VIEW IF EXISTS league_standings;
--
-- No hay nada más que ejecutar de este archivo — se conserva solo como
-- registro histórico de qué existía y por qué se quitó.
